import {requireNativeComponent} from 'react-native';
export default {
  XImage: require('../assets/images/Ximage.png'),
  CurrencyPana: require('../assets/images/Currencypana.png'),
  MobileLoginimage: require('../assets/images/Mobilelogin.png'),
  ArrowLeft: require('../assets/images/arrowleft.png'),
  SecureLogin: require('../assets/images/Securelogin.png'),
  SavingMoney: require('../assets/images/Savingmoney.png'),
  MobileLoginpana: require('../assets/images/Mobileloginpana.png'),
  AlignJustify: require('../assets/images/alignjustify.png'),
  AlJadeed: require('../assets/images/aljadeed.png'),
  ArrowDown: require('../assets/images/arrowdown.png'),
  ArrowRight: require('../assets/images/arrowright.png'),
  DunkinDonuts: require('../assets/images/dunkindonuts.png'),
  HeartImage: require('../assets/images/heartimage.png'),
  Path: require('../assets/images/path.png'),
  Star: require('../assets/images/starimage.png'),
  WalMart: require('../assets/images/walmart.png'),
  MapPin: require('../assets/images/mappinimage.png'),
  EWallet: require('../assets/images/EWallet.png'),
  Search: require('../assets/images/searchimage.png'),
  FashionImage: require('../assets/images/fashionimage.png'),
  Resturants: require('../assets/images/resturantimage.png'),
  Groceries: require('../assets/images/groceries.png'),
  SuperMarket: require('../assets/images/supermarketimage.png'),
  StarBucks: require('../assets/images/starBucks.png'),
  ChingGrill: require('../assets/images/chinggrill.png'),
  BurgerKing: require('../assets/images/burgerKing.png'),
  StarBucksResturants: require('../assets/images/starBucksResturant.png'),
  Ximage: require('../assets/images/x.png'),
  User: require('../assets/images/userimage.png'),
  Bellimage: require('../assets/images/bellimage.png'),
  FileKey: require('../assets/images/filekey.png'),
  HeartHandShake: require('../assets/images/hearthandshake.png'),
  AlertCircle: require('../assets/images/alertcircle.png'),
  JohnDoeImage: require('../assets/images/johnDoeImage.png'),
  ForwardArrow: require('../assets/images/forwardarrow.png'),
  AljadeedLogo: require('../assets/images/aljadeedLogo.png'),
  WalmartLogo: require('../assets/images/walmartLogo.png'),
  DunkinLogo: require('../assets/images/dunkinLogo.png'),
  ChinggrilLogo: require('../assets/images/chinggrillLogo.png'),
  BurgerkingLogo: require('../assets/images/burgerkingLogo.png'),
  Micheal: require('../assets/images/micheal.png'),
  Dollars: require('../assets/images/dollars.png'),
  Upload: require('../assets/images/uploadimage.png'),
  QRCodeImage: require('../assets/images/qrcodeimage.png'),
  WeekEndOffers: require('../assets/images/weekendoffers.png'),
  DailyOffer: require('../assets/images/dailyoffer.png'),
  EidOffer: require('../assets/images/eidoffer.png'),
  WeekEndOffer: require('../assets/images/weekendoffer.png'),
  WadeWarren: require('../assets/images/wadewaren.png'),
  JaneCooper: require('../assets/images/janecoper.png'),
  RobertFox: require('../assets/images/robert.png'),

  Cameron: require('../assets/images/cameron.png'),






};
